trigger:
  - main

pool:
  name: Default

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '8.x'

  - script: dotnet restore StringLibrary/StringLibrary.csproj
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Restore StringLibrary'

  - script: dotnet restore StringConsole/StringConsole.csproj
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Restore StringConsole'

  - script: dotnet build StringLibrary/StringLibrary.csproj -c Release
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Build StringLibrary'

  - script: dotnet pack StringLibrary/StringLibrary.csproj -c Release -o $(Build.ArtifactStagingDirectory)
    workingDirectory: $(Build.SourcesDirectory)
    displayName: 'Pack StringLibrary'

  - task: NuGetAuthenticate@1
    displayName: 'Authenticate with Azure Artifacts'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: 'd923df66-bec9-4a67-97af-001198209c3b/d41fa06e-361a-4a52-9bf1-fe0abc7e749b'


 